# Generated by Django 4.1.3 on 2022-12-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_campania_sport', '0002_articlestocampaniasport_monuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlesToCampaniaSport',
        ),
    ]
