# Generated by Django 4.1.3 on 2022-12-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_campania_sport', '0003_delete_articlestocampaniasport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaniasportarticles',
            name='date',
        ),
        migrations.RemoveField(
            model_name='campaniasportarticles',
            name='image',
        ),
        migrations.AddField(
            model_name='campaniasportarticles',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
