# Generated by Django 4.1.3 on 2022-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_campania_sport', '0005_remove_campaniasportarticles_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaniasportarticles',
            name='article_url',
            field=models.TextField(null=True),
        ),
    ]
