# Generated by Django 4.1.3 on 2023-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("coordinate", models.CharField(max_length=300)),
                ("url_image", models.CharField(max_length=300)),
                ("description", models.TextField()),
            ],
        ),
    ]
