# Generated by Django 4.1.3 on 2023-05-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircrafts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Flights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_from", models.CharField(max_length=10)),
                ("_from_city", models.TextField(blank=True)),
                ("to", models.CharField(max_length=10)),
                ("to_city", models.TextField(blank=True)),
                ("starting_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "aircraft_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aviation_management_system.aircrafts",
                    ),
                ),
            ],
        ),
    ]
