# Generated by Django 4.1.3 on 2023-06-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aviation_management_system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flights",
            old_name="_from_city",
            new_name="_from_coordinate",
        ),
        migrations.RenameField(
            model_name="flights",
            old_name="to_city",
            new_name="_to_coordinate",
        ),
    ]
