# Generated by Django 2.2.28 on 2022-09-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
