# Generated by Django 2.2.28 on 2022-09-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_blogarticles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
