# Generated by Django 2.2.28 on 2022-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20220905_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
