# Generated by Django 2.2.28 on 2022-09-12 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20220905_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
