# Generated by Django 4.1.3 on 2022-12-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20220912_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticles',
            name='image',
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
