# Generated by Django 4.1.3 on 2023-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0007_remove_blogarticles_image_blogarticles_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GftMessages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet", models.CharField(max_length=300)),
            ],
        ),
    ]
